apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello-world
  namespace: nginx-demo
  labels:
    app: nginx-hello-world
spec:
  template:
    metadata:
      name: nginx-hello-world
      labels:
        costcenter: samp
        tier: front-end
    spec:
      containers:
        - name: nginx-hello-world
          image: nginxdemos/hello
  replicas: 2
  selector:
    matchLabels:
      app: nginx-hello-world
      costcenter: samp
      tier: front-end