apiVersion: v1
kind: Service
metadata:
  name: nginx-hello-world
  namespace: nginx-demo
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
      name: webport
  selector:
      app: nginx-hello-world
      costcenter: samp
      tier: front-end